import { expect, test } from '../../../shared/test.js';

/**
 * Characterization baseline for the widget tree, per route.
 *
 * This is not a behaviour test — it asserts nothing about what the tree
 * *should* contain. It pins what the current (pre-Puck) pipeline actually
 * produces so the migration has something to diff against. The Puck
 * migration replaces `widget_instance`/`widget_placement` with Puck
 * documents; the converted output must reproduce this tree exactly, and the
 * failure mode it guards against is silent content loss — a nested child
 * dropped, a container flattened, an ordering inverted — none of which throws.
 *
 * Why the GraphQL tree and not rendered HTML: rendered markup carries live
 * catalog data, prices, session ids and timestamps, so a committed HTML
 * snapshot would churn constantly and teach everyone to ignore it. The widget
 * tree is the thing both pipelines must agree on, and it is stable. Phase 2's
 * HTML byte-diff is the complement — it compares the two pipelines against
 * each other *at the same instant*, which is a different job from a committed
 * baseline.
 *
 * Snapshots live in `__snapshots__/`. On a store whose page-builder content
 * differs from this one they will legitimately differ; regenerate with
 * `npx playwright test <this file> --update-snapshots` and review the diff —
 * that review is the point.
 */

/** Every route id the RRv7 storefront mounts a `WidgetArea` on (`const ROUTE_ID` in routes/*.tsx). */
const ROUTE_IDS = [
  'homepage',
  'productView',
  'categoryView',
  'catalogSearch',
  'cart',
  'cmsPageView',
  'blogHome',
  'blogPostView',
  'account'
] as const;

const WIDGETS_FOR_ROUTE = `
  query Characterize($route: String!) {
    widgetsForRoute(route: $route) {
      type
      status
      placements { area sortOrder entityUrn }
      columns {
        index
        widgets {
          type
          placements { area sortOrder entityUrn }
          columns { index widgets { type placements { area sortOrder entityUrn } } }
        }
      }
    }
  }
`;

interface RawWidget {
  type: string;
  status?: number;
  placements: { area: string; sortOrder: number; entityUrn: string | null }[];
  columns?: { index: number; widgets: RawWidget[] }[];
}

/**
 * Strip everything non-structural. uuids are deliberately dropped — they are
 * regenerated by seeds and clones, so including them would make the snapshot
 * machine-specific without adding signal. What matters is type, position and
 * nesting.
 */
function normalize(widgets: RawWidget[]): unknown[] {
  return widgets.map((w) => ({
    type: w.type,
    placements: [...(w.placements ?? [])]
      .map((p) => ({ area: p.area, sortOrder: p.sortOrder, scoped: p.entityUrn !== null }))
      .sort((a, b) => a.area.localeCompare(b.area) || a.sortOrder - b.sortOrder),
    columns: (w.columns ?? [])
      .slice()
      .sort((a, b) => a.index - b.index)
      .map((c) => ({ index: c.index, widgets: normalize(c.widgets ?? []) }))
  }));
}

test.describe('widget tree characterization (pre-Puck baseline)', () => {
  for (const route of ROUTE_IDS) {
    test(`${route}: widget tree is unchanged`, async ({ request }) => {
      const res = await request.post('/api/graphql', {
        data: { query: WIDGETS_FOR_ROUTE, variables: { route } }
      });
      expect(res.ok()).toBe(true);

      const body = (await res.json()) as {
        data?: { widgetsForRoute: RawWidget[] };
        errors?: unknown;
      };
      // A GraphQL-level error would otherwise surface as an empty tree, which
      // snapshots just as happily as a genuinely empty route.
      expect(body.errors, `GraphQL errors for ${route}`).toBeUndefined();

      const tree = normalize(body.data?.widgetsForRoute ?? []);
      expect(JSON.stringify(tree, null, 2)).toMatchSnapshot(`${route}.json`);
    });
  }

  test('every seeded widget type is registered on the storefront', async ({
    request
  }) => {
    // Guards the failure mode where a widget row exists for a type nothing can
    // render: `WidgetArea` returns null for an unregistered type, so the
    // content disappears with no error. Worth pinning before the Puck config
    // is generated from this same type set.
    const types = new Set<string>();
    for (const route of ROUTE_IDS) {
      const res = await request.post('/api/graphql', {
        data: { query: WIDGETS_FOR_ROUTE, variables: { route } }
      });
      const body = (await res.json()) as { data?: { widgetsForRoute: RawWidget[] } };
      const collect = (ws: RawWidget[]) => {
        for (const w of ws) {
          types.add(w.type);
          for (const c of w.columns ?? []) collect(c.widgets ?? []);
        }
      };
      collect(body.data?.widgetsForRoute ?? []);
    }
    expect(JSON.stringify([...types].sort(), null, 2)).toMatchSnapshot(
      'registered-types.json'
    );
  });
});
